### ISSUE TITLE
请问如何回退到上个版本？

### ISSUE THREAD

**Issue by wangyongshuai88** [qinyongliang/suspension-utools#16]
我的使用场景是 win10  多个虚拟桌面的标记。
每个桌面上悬浮1个的标记。
更新以后，现在图片恒定的悬浮在每个桌面之上。没有办法当作标记了。

**Comment by qinyongliang** [comment]
https://github.com/marsvet/uTools-plugins-collection/blob/master/plugins/%E6%82%AC%E6%B5%AE-v1.2.8.upx
