### ISSUE TITLE
求大佬还原一个过去版本的功能

### ISSUE THREAD

**Issue by wangyongshuai88** [qinyongliang/suspension-utools#18]
我有一个悬浮-v1.2.8版本的使用场景：
在使用win10的时候，使用这个版本，可以在多个虚拟桌面上分别悬浮一个标记。这样就可以随时知道自己处于哪个虚拟桌面上。
但是现在使用win11以后，v1.2.8 版本失效了。新版本的悬浮会同时悬浮在所有的虚拟桌面上，不受虚拟桌面切换的控制。
求大佬增加一个设置按钮，可以选择悬浮方案。感激不尽

**Comment by qinyongliang** [comment]
[悬浮-1.9.0.zip](https://github.com/qinyongliang/suspension-utools/files/11297050/-1.9.0.zip)
解压后手动安装试试

**Comment by wangyongshuai88** [comment]
哇，终于好了，太感谢了。大佬牛啊。效率杠杠滴！！！！！
