### ISSUE TITLE
keepass 问题

### ISSUE THREAD

**Issue by ACodingJie** [qinyongliang/suspension-utools#3]
1. 如下图所示 基本上每次使用自动输入的方式 第一个密码都会丢失, 盲猜是输入法的影响, 期望修复
![image](https://user-images.githubusercontent.com/44465791/105278454-7e9dba00-5be0-11eb-9de2-2ad248d84797.png)

**Comment by ACodingJie** [comment]
QQ输入法 中文模式, 输入就有问题, 英文模式没有问题

**Comment by qinyongliang** [comment]
这是图片悬浮项目。你应该提错了。
你可以将此分组的自动键入设置修改以下，在输入密码之前将使用模拟模拟按键，将输入法切换成英文模式。
