### ISSUE TITLE
Windows10上无法从剪切板悬浮图片

### ISSUE THREAD

**Issue by chenpey** [qinyongliang/suspension-utools#6]
只有截图并悬浮生效，请问这个可以修复一下吗？谢谢
![image](https://user-images.githubusercontent.com/12902930/114330160-b0854380-9b73-11eb-9f1b-0d1febe6e287.png)

**Comment by qinyongliang** [comment]
我在本地win10是可以的，你的操作是，截图-->呼出utools-->(自动)粘贴图片 嘛？

**Comment by chenpey** [comment]
> 我在本地win10是可以的，你的操作是，截图-->呼出utools-->(自动)粘贴图片 嘛？

截图保存到剪切板，-->呼出utools-->输入 悬浮
然后就只有 截图并悬浮
点击就只能再截图
而不是把剪切板里面的图悬浮

**Comment by qinyongliang** [comment]
使用utools的方式错误了。是呼出utools，按ctrl+v将剪切板图片粘贴到utools输入框中后，才会有针对此图片的操作，比如悬浮、ocr等
